/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jomari
 */
public class AdmissionDocuments extends javax.swing.JFrame {

    /**
     * Creates new form AdmissionDocuments
     */
    public AdmissionDocuments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBarPanel = new javax.swing.JPanel();
        PCULabel = new javax.swing.JLabel();
        PCULogoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        OriginalLabel = new javax.swing.JLabel();
        RequiredDocumentLabel = new javax.swing.JLabel();
        number1Label = new javax.swing.JLabel();
        PreviousLabel = new javax.swing.JLabel();
        number3Label = new javax.swing.JLabel();
        number4Label = new javax.swing.JLabel();
        ForTransfereeLabel = new javax.swing.JLabel();
        CertificateLabel = new javax.swing.JLabel();
        AlternativeLabel = new javax.swing.JLabel();
        TORLabel = new javax.swing.JLabel();
        FileFormatLabel = new javax.swing.JLabel();
        MaximumLabel = new javax.swing.JLabel();
        UploadFileLabel = new javax.swing.JLabel();
        number2Label = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(968, 732));
        setSize(new java.awt.Dimension(968, 732));

        TopBarPanel.setBackground(new java.awt.Color(87, 123, 247));

        PCULabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        PCULabel.setForeground(new java.awt.Color(255, 255, 255));
        PCULabel.setText("Philippine Christian University");

        PCULogoLabel.setIcon(new javax.swing.ImageIcon("/Users/jomari/Downloads/Philippine_Christian_University_60.png")); // NOI18N

        javax.swing.GroupLayout TopBarPanelLayout = new javax.swing.GroupLayout(TopBarPanel);
        TopBarPanel.setLayout(TopBarPanelLayout);
        TopBarPanelLayout.setHorizontalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(PCULogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PCULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBarPanelLayout.setVerticalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PCULabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PCULogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));

        OriginalLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        OriginalLabel.setForeground(new java.awt.Color(0, 0, 0));
        OriginalLabel.setText("Original and Scanned Copy of the following:");

        RequiredDocumentLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        RequiredDocumentLabel.setForeground(new java.awt.Color(0, 0, 0));
        RequiredDocumentLabel.setText("Required Admission Documents:");

        number1Label.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        number1Label.setForeground(new java.awt.Color(0, 0, 0));
        number1Label.setText("1. Duly filled-out Application Form (from the website)");

        PreviousLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PreviousLabel.setForeground(new java.awt.Color(51, 153, 255));
        PreviousLabel.setText("Previous");

        number3Label.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        number3Label.setForeground(new java.awt.Color(0, 0, 0));
        number3Label.setText("3. PSA Birth Certificate");

        number4Label.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        number4Label.setForeground(new java.awt.Color(0, 0, 0));
        number4Label.setText("4. Report Card/Rating Form/TOR: ");

        ForTransfereeLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        ForTransfereeLabel.setForeground(new java.awt.Color(0, 0, 0));
        ForTransfereeLabel.setText("*FOR TRANSFEREES & SECOND-COURSE TAKERS");

        CertificateLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        CertificateLabel.setForeground(new java.awt.Color(0, 0, 0));
        CertificateLabel.setText("*Certificate of Rating (ALS Passers)-must indicate “Eligible for College Admission” ");

        AlternativeLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        AlternativeLabel.setForeground(new java.awt.Color(0, 0, 0));
        AlternativeLabel.setText("*FOR ALTERNATIVE LEARNING SYSTEM (ALS) PASSERS");

        TORLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        TORLabel.setForeground(new java.awt.Color(0, 0, 0));
        TORLabel.setText("*Transcript of Records (TOR) – from previous college/university");

        FileFormatLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        FileFormatLabel.setForeground(new java.awt.Color(0, 0, 0));
        FileFormatLabel.setText("*File format in JPEG(.jpg), PNG & PDF are the only acceptable file for upload.");

        MaximumLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        MaximumLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaximumLabel.setText("*Maximum of 1mb file size per upload.");

        UploadFileLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        UploadFileLabel.setForeground(new java.awt.Color(51, 153, 255));
        UploadFileLabel.setText("Upload File / Add Atachment");

        number2Label.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        number2Label.setForeground(new java.awt.Color(0, 0, 0));
        number2Label.setText("2. Recent 2x2 ID picture with student's name tag, white background, 2 copies");

        NextLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NextLabel.setForeground(new java.awt.Color(51, 153, 255));
        NextLabel.setText("Next");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UploadFileLabel)
                                    .addComponent(number4Label)
                                    .addComponent(number3Label)
                                    .addComponent(number2Label)
                                    .addComponent(FileFormatLabel)
                                    .addComponent(MaximumLabel)
                                    .addComponent(number1Label)
                                    .addComponent(RequiredDocumentLabel)
                                    .addComponent(OriginalLabel))
                                .addGap(0, 154, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PreviousLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NextLabel)
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(CertificateLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ForTransfereeLabel)
                            .addComponent(AlternativeLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(TORLabel)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RequiredDocumentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(OriginalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number1Label)
                        .addGap(9, 9, 9)))
                .addGap(3, 3, 3)
                .addComponent(number2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number4Label)
                .addGap(18, 18, 18)
                .addComponent(AlternativeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CertificateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ForTransfereeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TORLabel)
                .addGap(18, 18, 18)
                .addComponent(FileFormatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaximumLabel)
                .addGap(18, 18, 18)
                .addComponent(UploadFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousLabel)
                    .addComponent(NextLabel))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmissionDocuments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmissionDocuments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmissionDocuments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmissionDocuments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmissionDocuments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlternativeLabel;
    private javax.swing.JLabel CertificateLabel;
    private javax.swing.JLabel FileFormatLabel;
    private javax.swing.JLabel ForTransfereeLabel;
    private javax.swing.JLabel MaximumLabel;
    private javax.swing.JLabel NextLabel;
    private javax.swing.JLabel OriginalLabel;
    public javax.swing.JLabel PCULabel;
    public javax.swing.JLabel PCULogoLabel;
    private javax.swing.JLabel PreviousLabel;
    private javax.swing.JLabel RequiredDocumentLabel;
    private javax.swing.JLabel TORLabel;
    private javax.swing.JPanel TopBarPanel;
    private javax.swing.JLabel UploadFileLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel number1Label;
    private javax.swing.JLabel number2Label;
    private javax.swing.JLabel number3Label;
    private javax.swing.JLabel number4Label;
    // End of variables declaration//GEN-END:variables
}
