/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group1.studentinfosystem;

/**
 *
 * @author joshu
 */
public class ApplicationStart extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationStart
     */
    public ApplicationStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBarPanel = new javax.swing.JPanel();
        PCULabel = new javax.swing.JLabel();
        PCULogoLabel = new javax.swing.JLabel();
        FirstChoiceLabel = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        SchoolLabel = new javax.swing.JLabel();
        ProgramLabel = new javax.swing.JLabel();
        AcademicProgramLabel = new javax.swing.JLabel();
        AcademicProgramComboBox = new javax.swing.JComboBox<>();
        CampusComboBox = new javax.swing.JComboBox<>();
        ProgramComboBox = new javax.swing.JComboBox<>();
        ApplicationTypeComboBox = new javax.swing.JComboBox<>();
        PleaseCompleteLabel = new javax.swing.JLabel();
        ApplicationTypeLabel = new javax.swing.JLabel();
        LevelComboBox = new javax.swing.JComboBox<>();
        NextLabel = new javax.swing.JLabel();
        ReturnLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(967, 617));
        setResizable(false);
        setSize(new java.awt.Dimension(967, 617));
        getContentPane().setLayout(null);

        TopBarPanel.setBackground(new java.awt.Color(86, 123, 247));

        PCULabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        PCULabel.setForeground(new java.awt.Color(255, 255, 255));
        PCULabel.setText("Philippine Christian University");

        PCULogoLabel.setIcon(new javax.swing.ImageIcon("/Users/jomari/Downloads/Philippine_Christian_University_60.png")); // NOI18N

        javax.swing.GroupLayout TopBarPanelLayout = new javax.swing.GroupLayout(TopBarPanel);
        TopBarPanel.setLayout(TopBarPanelLayout);
        TopBarPanelLayout.setHorizontalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(PCULogoLabel)
                .addGap(12, 12, 12)
                .addComponent(PCULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBarPanelLayout.setVerticalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PCULogoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TopBarPanelLayout.createSequentialGroup()
                .addComponent(PCULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(TopBarPanel);
        TopBarPanel.setBounds(0, 0, 880, 80);

        FirstChoiceLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        FirstChoiceLabel.setForeground(new java.awt.Color(0, 0, 0));
        FirstChoiceLabel.setText("First Choice:");
        getContentPane().add(FirstChoiceLabel);
        FirstChoiceLabel.setBounds(40, 290, 190, 36);

        LevelLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LevelLabel.setText("Level:");
        getContentPane().add(LevelLabel);
        LevelLabel.setBounds(160, 250, 50, 30);

        SchoolLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SchoolLabel.setText("School Campus:");
        getContentPane().add(SchoolLabel);
        SchoolLabel.setBounds(80, 160, 140, 22);

        ProgramLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ProgramLabel.setText("Education Program:");
        getContentPane().add(ProgramLabel);
        ProgramLabel.setBounds(50, 192, 170, 20);

        AcademicProgramLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AcademicProgramLabel.setText("Academic Program:");
        getContentPane().add(AcademicProgramLabel);
        AcademicProgramLabel.setBounds(50, 330, 170, 30);

        AcademicProgramComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Academic Program", "Bachelor of Arts in English Language Studies", "Bachelor of Arts in Broadcasting", "Bachelor of Arts in Political Science", "Bachelor of Arts in Psychology", "Bachelor of Arts in Philosophy", "Bachelor of Science in Biology", "Bachelor of Science in Accountancy", "Bachelor of Science in Business Administration", "Major in Marketing Management", "Major in Operations Management", "Major in Financial Management", "Bachelor of Science in Customs Administration", "Bachelor of Science in Real Estate Management", "Bachelor of Elementary Education", "Bachelor of Secondary Education", "Majors in English, Mathematics, Science, and other fields", "Bachelor of Science in Nursing", "Bachelor of Science in Hospitality Management", "Bachelor of Science in Tourism Management", "Associate in Cruise Line Management", "Bachelor of Science in Information Technology", "Bachelor of Science in Computer Science", "Bachelor of Science in Computer Engineering", "Bachelor in Multimedia Arts", "Bachelor of Science in Criminology", "Bachelor of Science in Social Work", "Bachelor of Arts in Church Management", "Juris Doctor" }));
        AcademicProgramComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcademicProgramComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(AcademicProgramComboBox);
        AcademicProgramComboBox.setBounds(220, 330, 580, 30);

        CampusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Campus", "Manila", "Dasmariñas" }));
        CampusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampusComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(CampusComboBox);
        CampusComboBox.setBounds(220, 158, 580, 27);

        ProgramComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Program", "Bachelor of Arts in English Language Studies", "Bachelor of Arts in Broadcasting", "Bachelor of Arts in Political Science", "Bachelor of Arts in Psychology", "Bachelor of Arts in Philosophy", "Bachelor of Science in Biology", "Bachelor of Science in Accountancy", "Bachelor of Science in Business Administration", "Major in Marketing Management", "Major in Operations Management", "Major in Financial Management", "Bachelor of Science in Customs Administration", "Bachelor of Science in Real Estate Management", "Bachelor of Elementary Education", "Bachelor of Secondary Education", "Majors in English, Mathematics, Science, and other fields", "Bachelor of Science in Nursing", "Bachelor of Science in Hospitality Management", "Bachelor of Science in Tourism Management", "Associate in Cruise Line Management", "Bachelor of Science in Information Technology", "Bachelor of Science in Computer Science", "Bachelor of Science in Computer Engineering", "Bachelor in Multimedia Arts", "Bachelor of Science in Criminology", "Bachelor of Science in Social Work", "Bachelor of Arts in Church Management", "Juris Doctor" }));
        ProgramComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ProgramComboBox);
        ProgramComboBox.setBounds(220, 190, 580, 27);

        ApplicationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Application Type", "College - Freshman", "College - Transferee", "College - 2nd Courser", "College - Cross Enrollee", "Returnee", "Program for Accelerated College Education (PACE)", "Expanded Tertiary Education Equivalency and Accreditation Program (ETEEAP)", "University Academic Extension Programs", "Pure Online/Modular - Graduate School" }));
        ApplicationTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplicationTypeComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ApplicationTypeComboBox);
        ApplicationTypeComboBox.setBounds(220, 220, 580, 27);

        PleaseCompleteLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        PleaseCompleteLabel.setForeground(new java.awt.Color(0, 0, 0));
        PleaseCompleteLabel.setText("Please complete the form for you application: ");
        getContentPane().add(PleaseCompleteLabel);
        PleaseCompleteLabel.setBounds(40, 100, 660, 36);

        ApplicationTypeLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ApplicationTypeLabel.setText("Application Type:");
        getContentPane().add(ApplicationTypeLabel);
        ApplicationTypeLabel.setBounds(70, 220, 150, 30);

        LevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "1st Year", "2nd Year", "3rd Year", "4th Year", "Masteral", "Juris Doctor" }));
        LevelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(LevelComboBox);
        LevelComboBox.setBounds(220, 250, 580, 27);

        NextLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NextLabel.setForeground(new java.awt.Color(51, 153, 255));
        NextLabel.setText("Next");
        getContentPane().add(NextLabel);
        NextLabel.setBounds(770, 390, 30, 20);

        ReturnLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ReturnLabel.setForeground(new java.awt.Color(51, 153, 255));
        ReturnLabel.setText("Return to Login");
        getContentPane().add(ReturnLabel);
        ReturnLabel.setBounds(50, 390, 110, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcademicProgramComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcademicProgramComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcademicProgramComboBoxActionPerformed

    private void CampusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampusComboBoxActionPerformed

    private void ProgramComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramComboBoxActionPerformed

    private void ApplicationTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplicationTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApplicationTypeComboBoxActionPerformed

    private void LevelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevelComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> AcademicProgramComboBox;
    public javax.swing.JLabel AcademicProgramLabel;
    public javax.swing.JComboBox<String> ApplicationTypeComboBox;
    public javax.swing.JLabel ApplicationTypeLabel;
    private javax.swing.JComboBox<String> CampusComboBox;
    public javax.swing.JLabel FirstChoiceLabel;
    public javax.swing.JComboBox<String> LevelComboBox;
    private javax.swing.JLabel LevelLabel;
    public javax.swing.JLabel NextLabel;
    public javax.swing.JLabel PCULabel;
    public javax.swing.JLabel PCULogoLabel;
    public javax.swing.JLabel PleaseCompleteLabel;
    public javax.swing.JComboBox<String> ProgramComboBox;
    public javax.swing.JLabel ProgramLabel;
    public javax.swing.JLabel ReturnLabel;
    public javax.swing.JLabel SchoolLabel;
    public javax.swing.JPanel TopBarPanel;
    // End of variables declaration//GEN-END:variables
}
