/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group1.studentinfosystem;

/**
 *
 * @author joshu
 */
public class educationalbackground extends javax.swing.JFrame {

    /**
     * Creates new form educationalbackground
     */
    public educationalbackground() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBarPanel = new javax.swing.JPanel();
        PCULabel = new javax.swing.JLabel();
        PCULogoLabel = new javax.swing.JLabel();
        EducationalBackgroundLabel = new javax.swing.JLabel();
        PrivateSchoolCheckBox1 = new javax.swing.JCheckBox();
        PreviouSchoolTextField = new javax.swing.JTextField();
        PreviousSchoolLabel = new javax.swing.JLabel();
        SchoolAddressTextField = new javax.swing.JTextField();
        SchoolAddressLabel = new javax.swing.JLabel();
        StrandTextField = new javax.swing.JTextField();
        Strand = new javax.swing.JLabel();
        YearOfGraduationTextField = new javax.swing.JTextField();
        YearOfGraduationLabel = new javax.swing.JLabel();
        GWATextField = new javax.swing.JTextField();
        GWALabel = new javax.swing.JLabel();
        AwardLabel = new javax.swing.JLabel();
        HonorTextField = new javax.swing.JTextField();
        IfTransfereeLabel = new javax.swing.JLabel();
        SchoolAddressTLabel = new javax.swing.JLabel();
        AwardTLabel = new javax.swing.JLabel();
        StrandTTextBox = new javax.swing.JTextField();
        AwardTTextField = new javax.swing.JTextField();
        StrandTLabel = new javax.swing.JLabel();
        YearOfGraduationTTextField = new javax.swing.JTextField();
        ReasonLabel = new javax.swing.JLabel();
        GWATTextField = new javax.swing.JTextField();
        PrivateSchoolTCheckBox = new javax.swing.JCheckBox();
        GWATLabel = new javax.swing.JLabel();
        PreviousSchoolTTextField = new javax.swing.JTextField();
        PreviousSchoolTLabel = new javax.swing.JLabel();
        SchoolAddressTTextField = new javax.swing.JTextField();
        ReasonTextField = new javax.swing.JTextField();
        YearofGraduationTLabel = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();
        PreviousLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(986, 1287));

        TopBarPanel.setBackground(new java.awt.Color(86, 123, 247));

        PCULabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        PCULabel.setForeground(new java.awt.Color(255, 255, 255));
        PCULabel.setText("Philippine Christian University");

        PCULogoLabel.setIcon(new javax.swing.ImageIcon("/Users/jomari/Downloads/Philippine_Christian_University_60.png")); // NOI18N

        javax.swing.GroupLayout TopBarPanelLayout = new javax.swing.GroupLayout(TopBarPanel);
        TopBarPanel.setLayout(TopBarPanelLayout);
        TopBarPanelLayout.setHorizontalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(PCULogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PCULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        TopBarPanelLayout.setVerticalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarPanelLayout.createSequentialGroup()
                .addComponent(PCULogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(TopBarPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PCULabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EducationalBackgroundLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        EducationalBackgroundLabel.setForeground(new java.awt.Color(0, 0, 0));
        EducationalBackgroundLabel.setText("Educational Background:");

        PrivateSchoolCheckBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PrivateSchoolCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        PrivateSchoolCheckBox1.setText("Private School:");
        PrivateSchoolCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrivateSchoolCheckBox1ActionPerformed(evt);
            }
        });

        PreviouSchoolTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviouSchoolTextFieldActionPerformed(evt);
            }
        });

        PreviousSchoolLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PreviousSchoolLabel.setForeground(new java.awt.Color(0, 0, 0));
        PreviousSchoolLabel.setText("Previous School Attended:");

        SchoolAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolAddressTextFieldActionPerformed(evt);
            }
        });

        SchoolAddressLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SchoolAddressLabel.setForeground(new java.awt.Color(0, 0, 0));
        SchoolAddressLabel.setText("School Address:");

        StrandTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrandTextFieldActionPerformed(evt);
            }
        });

        Strand.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Strand.setForeground(new java.awt.Color(0, 0, 0));
        Strand.setText("Strand:");

        YearOfGraduationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearOfGraduationTextFieldActionPerformed(evt);
            }
        });

        YearOfGraduationLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        YearOfGraduationLabel.setForeground(new java.awt.Color(0, 0, 0));
        YearOfGraduationLabel.setText("Year of Graduation:");

        GWATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GWATextFieldActionPerformed(evt);
            }
        });

        GWALabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GWALabel.setForeground(new java.awt.Color(0, 0, 0));
        GWALabel.setText("GWA:");

        AwardLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AwardLabel.setForeground(new java.awt.Color(0, 0, 0));
        AwardLabel.setText("Award/Honor:");

        HonorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HonorTextFieldActionPerformed(evt);
            }
        });

        IfTransfereeLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        IfTransfereeLabel.setForeground(new java.awt.Color(0, 0, 0));
        IfTransfereeLabel.setText("If Transferee:");

        SchoolAddressTLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SchoolAddressTLabel.setForeground(new java.awt.Color(0, 0, 0));
        SchoolAddressTLabel.setText("School Address:");

        AwardTLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AwardTLabel.setForeground(new java.awt.Color(0, 0, 0));
        AwardTLabel.setText("Award/Honor:");

        StrandTTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrandTTextBoxActionPerformed(evt);
            }
        });

        AwardTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AwardTTextFieldActionPerformed(evt);
            }
        });

        StrandTLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        StrandTLabel.setForeground(new java.awt.Color(0, 0, 0));
        StrandTLabel.setText("Strand:");

        YearOfGraduationTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearOfGraduationTTextFieldActionPerformed(evt);
            }
        });

        ReasonLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ReasonLabel.setForeground(new java.awt.Color(0, 0, 0));
        ReasonLabel.setText("Reason for Transferring:");

        GWATTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GWATTextFieldActionPerformed(evt);
            }
        });

        PrivateSchoolTCheckBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PrivateSchoolTCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        PrivateSchoolTCheckBox.setText("Private School:");
        PrivateSchoolTCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrivateSchoolTCheckBoxActionPerformed(evt);
            }
        });

        GWATLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GWATLabel.setForeground(new java.awt.Color(0, 0, 0));
        GWATLabel.setText("GWA:");

        PreviousSchoolTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousSchoolTTextFieldActionPerformed(evt);
            }
        });

        PreviousSchoolTLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PreviousSchoolTLabel.setForeground(new java.awt.Color(0, 0, 0));
        PreviousSchoolTLabel.setText("Previous School Attended:");

        SchoolAddressTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolAddressTTextFieldActionPerformed(evt);
            }
        });

        ReasonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReasonTextFieldActionPerformed(evt);
            }
        });

        YearofGraduationTLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        YearofGraduationTLabel.setForeground(new java.awt.Color(0, 0, 0));
        YearofGraduationTLabel.setText("Year of Graduation:");

        NextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NextLabel.setForeground(new java.awt.Color(0, 153, 255));
        NextLabel.setText("Next");
        NextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextLabelMouseClicked(evt);
            }
        });

        PreviousLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PreviousLabel.setForeground(new java.awt.Color(0, 153, 255));
        PreviousLabel.setText("Previous");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EducationalBackgroundLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PreviouSchoolTextField)
                            .addComponent(ReasonTextField)
                            .addComponent(StrandTTextBox)
                            .addComponent(SchoolAddressTTextField)
                            .addComponent(PreviousSchoolTTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PreviousSchoolTLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PrivateSchoolTCheckBox))
                            .addComponent(StrandTextField)
                            .addComponent(SchoolAddressTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YearOfGraduationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(GWATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YearOfGraduationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(GWALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AwardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HonorTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YearOfGraduationTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(GWATTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YearofGraduationTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(GWATLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AwardTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AwardTTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ReasonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StrandTLabel)
                                    .addComponent(SchoolAddressTLabel)
                                    .addComponent(IfTransfereeLabel)
                                    .addComponent(Strand)
                                    .addComponent(SchoolAddressLabel))
                                .addGap(0, 437, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PreviousLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NextLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PreviousSchoolLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PrivateSchoolCheckBox1)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EducationalBackgroundLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrivateSchoolCheckBox1)
                    .addComponent(PreviousSchoolLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PreviouSchoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SchoolAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SchoolAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Strand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearOfGraduationLabel)
                    .addComponent(GWALabel)
                    .addComponent(AwardLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearOfGraduationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GWATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HonorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(IfTransfereeLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrivateSchoolTCheckBox)
                    .addComponent(PreviousSchoolTLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PreviousSchoolTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SchoolAddressTLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SchoolAddressTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StrandTLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StrandTTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GWATLabel)
                    .addComponent(AwardTLabel)
                    .addComponent(YearofGraduationTLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearOfGraduationTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GWATTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AwardTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ReasonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousLabel)
                    .addComponent(NextLabel))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrivateSchoolCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrivateSchoolCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrivateSchoolCheckBox1ActionPerformed

    private void PreviouSchoolTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviouSchoolTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviouSchoolTextFieldActionPerformed

    private void SchoolAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SchoolAddressTextFieldActionPerformed

    private void StrandTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrandTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StrandTextFieldActionPerformed

    private void YearOfGraduationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearOfGraduationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearOfGraduationTextFieldActionPerformed

    private void GWATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GWATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GWATextFieldActionPerformed

    private void HonorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HonorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HonorTextFieldActionPerformed

    private void StrandTTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrandTTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StrandTTextBoxActionPerformed

    private void AwardTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AwardTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AwardTTextFieldActionPerformed

    private void YearOfGraduationTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearOfGraduationTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearOfGraduationTTextFieldActionPerformed

    private void GWATTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GWATTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GWATTextFieldActionPerformed

    private void PrivateSchoolTCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrivateSchoolTCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrivateSchoolTCheckBoxActionPerformed

    private void PreviousSchoolTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousSchoolTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviousSchoolTTextFieldActionPerformed

    private void SchoolAddressTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolAddressTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SchoolAddressTTextFieldActionPerformed

    private void ReasonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReasonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReasonTextFieldActionPerformed

    private void NextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NextLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(educationalbackground.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(educationalbackground.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(educationalbackground.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(educationalbackground.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new educationalbackground().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel AwardLabel;
    private javax.swing.JLabel AwardTLabel;
    private javax.swing.JTextField AwardTTextField;
    public javax.swing.JLabel EducationalBackgroundLabel;
    public javax.swing.JLabel GWALabel;
    private javax.swing.JLabel GWATLabel;
    private javax.swing.JTextField GWATTextField;
    public javax.swing.JTextField GWATextField;
    private javax.swing.JTextField HonorTextField;
    public javax.swing.JLabel IfTransfereeLabel;
    private javax.swing.JLabel NextLabel;
    public javax.swing.JLabel PCULabel;
    public javax.swing.JLabel PCULogoLabel;
    public javax.swing.JTextField PreviouSchoolTextField;
    private javax.swing.JLabel PreviousLabel;
    public javax.swing.JLabel PreviousSchoolLabel;
    public javax.swing.JLabel PreviousSchoolTLabel;
    private javax.swing.JTextField PreviousSchoolTTextField;
    public javax.swing.JCheckBox PrivateSchoolCheckBox1;
    private javax.swing.JCheckBox PrivateSchoolTCheckBox;
    private javax.swing.JLabel ReasonLabel;
    private javax.swing.JTextField ReasonTextField;
    public javax.swing.JLabel SchoolAddressLabel;
    public javax.swing.JLabel SchoolAddressTLabel;
    private javax.swing.JTextField SchoolAddressTTextField;
    public javax.swing.JTextField SchoolAddressTextField;
    public javax.swing.JLabel Strand;
    private javax.swing.JLabel StrandTLabel;
    private javax.swing.JTextField StrandTTextBox;
    public javax.swing.JTextField StrandTextField;
    public javax.swing.JPanel TopBarPanel;
    public javax.swing.JLabel YearOfGraduationLabel;
    private javax.swing.JTextField YearOfGraduationTTextField;
    public javax.swing.JTextField YearOfGraduationTextField;
    private javax.swing.JLabel YearofGraduationTLabel;
    // End of variables declaration//GEN-END:variables
}
