/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group1.studentinfosystem;

/**
 *
 * @author joshu
 */
public class FamilyInformation extends javax.swing.JFrame {

    /**
     * Creates new form FamilyInformation
     */
    public FamilyInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        TopBarPanel = new javax.swing.JPanel();
        PCULabel = new javax.swing.JLabel();
        PCULogoLabel = new javax.swing.JLabel();
        EmergencyContactLabel = new javax.swing.JLabel();
        CompleteNameLabel = new javax.swing.JLabel();
        CompleteNameTextField = new javax.swing.JTextField();
        RelationshipComboBox = new javax.swing.JComboBox<>();
        RelationshipLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        TelephoneNumberLabel = new javax.swing.JLabel();
        TelelphoneNumberTextField = new javax.swing.JTextField();
        MobileNumberTextField = new javax.swing.JTextField();
        MobileNumberLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();
        PreviousLabel = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(968, 617));
        setSize(new java.awt.Dimension(968, 617));

        TopBarPanel.setBackground(new java.awt.Color(86, 123, 247));

        PCULabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        PCULabel.setForeground(new java.awt.Color(255, 255, 255));
        PCULabel.setText("Philippine Christian University");

        PCULogoLabel.setIcon(new javax.swing.ImageIcon("/Users/jomari/Downloads/Philippine_Christian_University_60.png")); // NOI18N

        javax.swing.GroupLayout TopBarPanelLayout = new javax.swing.GroupLayout(TopBarPanel);
        TopBarPanel.setLayout(TopBarPanelLayout);
        TopBarPanelLayout.setHorizontalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PCULogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PCULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBarPanelLayout.setVerticalGroup(
            TopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarPanelLayout.createSequentialGroup()
                .addComponent(PCULogoLabel)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(TopBarPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(PCULabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EmergencyContactLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        EmergencyContactLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmergencyContactLabel.setText("Emergency Contact:");

        CompleteNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CompleteNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        CompleteNameLabel.setText("Complete Name:");

        CompleteNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteNameTextFieldActionPerformed(evt);
            }
        });

        RelationshipComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RelationshipComboBox.setForeground(new java.awt.Color(0, 0, 0));
        RelationshipComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mother", "Father", "Sibling", "Other" }));

        RelationshipLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RelationshipLabel.setForeground(new java.awt.Color(0, 0, 0));
        RelationshipLabel.setText("Relationship:");

        AddressLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(0, 0, 0));
        AddressLabel.setText("Complete Address:");

        AddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextFieldActionPerformed(evt);
            }
        });

        TelephoneNumberLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TelephoneNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        TelephoneNumberLabel.setText("Telephone Number:");

        TelelphoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelelphoneNumberTextFieldActionPerformed(evt);
            }
        });

        MobileNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNumberTextFieldActionPerformed(evt);
            }
        });

        MobileNumberLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MobileNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        MobileNumberLabel.setText("MobileNumber:");

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        EmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel.setText("Email Address:");

        NextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NextLabel.setForeground(new java.awt.Color(0, 153, 255));
        NextLabel.setText("Next");

        PreviousLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PreviousLabel.setForeground(new java.awt.Color(0, 153, 255));
        PreviousLabel.setText("Previous");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AddressLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EmergencyContactLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CompleteNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CompleteNameLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RelationshipLabel)
                                .addComponent(RelationshipComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(AddressTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TelelphoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(TelephoneNumberLabel)
                                    .addGap(138, 138, 138)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MobileNumberLabel)
                                .addComponent(MobileNumberTextField)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(PreviousLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NextLabel))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmergencyContactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompleteNameLabel)
                    .addComponent(RelationshipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompleteNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelationshipComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelephoneNumberLabel)
                    .addComponent(MobileNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelelphoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextLabel)
                    .addComponent(PreviousLabel))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompleteNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompleteNameTextFieldActionPerformed

    private void AddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextFieldActionPerformed

    private void TelelphoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelelphoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelelphoneNumberTextFieldActionPerformed

    private void MobileNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNumberTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilyInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilyInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilyInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilyInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilyInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JLabel CompleteNameLabel;
    private javax.swing.JTextField CompleteNameTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel EmergencyContactLabel;
    private javax.swing.JLabel MobileNumberLabel;
    private javax.swing.JTextField MobileNumberTextField;
    private javax.swing.JLabel NextLabel;
    private javax.swing.JLabel PCULabel;
    private javax.swing.JLabel PCULogoLabel;
    private javax.swing.JLabel PreviousLabel;
    private javax.swing.JComboBox<String> RelationshipComboBox;
    private javax.swing.JLabel RelationshipLabel;
    private javax.swing.JTextField TelelphoneNumberTextField;
    private javax.swing.JLabel TelephoneNumberLabel;
    private javax.swing.JPanel TopBarPanel;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
