/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package group1.studentinfosystem;

/**
 *
 * @author jomari
 */
public class LoginPage extends javax.swing.JPanel {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        PCULogoLabel = new javax.swing.JLabel();
        ChristianLabel = new javax.swing.JLabel();
        UniversityLabel = new javax.swing.JLabel();
        PhillipineLabel = new javax.swing.JLabel();
        PanelFrame = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        RememberMeCheckBox = new javax.swing.JCheckBox();
        LoginButton = new javax.swing.JButton();
        ForgotPasswordLabel = new javax.swing.JLabel();
        DontHaveAccountYetLabel = new javax.swing.JLabel();
        CreateAccountButton = new javax.swing.JButton();
        PanelBar = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(967, 617));
        setPreferredSize(new java.awt.Dimension(967, 617));
        setSize(new java.awt.Dimension(967, 617));

        SideBar.setBackground(new java.awt.Color(87, 123, 247));

        PCULogoLabel.setIcon(new javax.swing.ImageIcon("/Users/jomari/Downloads/Philippine_Christian_University_logo.png")); // NOI18N

        ChristianLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        ChristianLabel.setForeground(new java.awt.Color(255, 255, 255));
        ChristianLabel.setText("Christian");

        UniversityLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        UniversityLabel.setForeground(new java.awt.Color(255, 255, 255));
        UniversityLabel.setText("University");

        PhillipineLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        PhillipineLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhillipineLabel.setText("Philippine");

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UniversityLabel)
                            .addGroup(SideBarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ChristianLabel))
                            .addComponent(PhillipineLabel)))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PCULogoLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(PCULogoLabel)
                .addGap(10, 10, 10)
                .addComponent(PhillipineLabel)
                .addGap(0, 0, 0)
                .addComponent(ChristianLabel)
                .addGap(0, 0, 0)
                .addComponent(UniversityLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelFrame.setBackground(new java.awt.Color(255, 255, 255));
        PanelFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelFrame.setForeground(new java.awt.Color(255, 255, 255));

        UsernameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setText("Username:");

        UsernameTextField.setBackground(new java.awt.Color(255, 255, 255));
        UsernameTextField.setForeground(new java.awt.Color(0, 0, 0));
        UsernameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PasswordLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setText("Password:");

        PasswordTextField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordTextField.setForeground(new java.awt.Color(0, 0, 0));
        PasswordTextField.setText("jPasswordField1");
        PasswordTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        RememberMeCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RememberMeCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        RememberMeCheckBox.setText("Remember me");
        RememberMeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RememberMeCheckBoxActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(87, 123, 247));
        LoginButton.setForeground(new java.awt.Color(0, 0, 0));
        LoginButton.setText("Login");

        ForgotPasswordLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ForgotPasswordLabel.setForeground(new java.awt.Color(51, 102, 255));
        ForgotPasswordLabel.setText("Forgot Password?");

        DontHaveAccountYetLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        DontHaveAccountYetLabel.setForeground(new java.awt.Color(0, 0, 0));
        DontHaveAccountYetLabel.setText("Don't have an account yet?");

        CreateAccountButton.setBackground(new java.awt.Color(87, 123, 247));
        CreateAccountButton.setForeground(new java.awt.Color(0, 0, 0));
        CreateAccountButton.setText("Create an Account (Freshmen, Transferee)");
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFrameLayout = new javax.swing.GroupLayout(PanelFrame);
        PanelFrame.setLayout(PanelFrameLayout);
        PanelFrameLayout.setHorizontalGroup(
            PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ForgotPasswordLabel)
                    .addGroup(PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelFrameLayout.createSequentialGroup()
                            .addComponent(RememberMeCheckBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoginButton))
                        .addGroup(PanelFrameLayout.createSequentialGroup()
                            .addGroup(PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PasswordLabel)
                                .addComponent(UsernameLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UsernameTextField)
                                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CreateAccountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DontHaveAccountYetLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        PanelFrameLayout.setVerticalGroup(
            PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFrameLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UsernameLabel)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(PanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RememberMeCheckBox))
                .addGap(42, 42, 42)
                .addComponent(ForgotPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(DontHaveAccountYetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        PanelBar.setBackground(new java.awt.Color(87, 123, 247));
        PanelBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LoginLabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(0, 0, 0));
        LoginLabel.setText("Login to your Account");

        javax.swing.GroupLayout PanelBarLayout = new javax.swing.GroupLayout(PanelBar);
        PanelBar.setLayout(PanelBarLayout);
        PanelBarLayout.setHorizontalGroup(
            PanelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LoginLabel)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        PanelBarLayout.setVerticalGroup(
            PanelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(PanelBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RememberMeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RememberMeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RememberMeCheckBoxActionPerformed

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAccountButtonActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ChristianLabel;
    public javax.swing.JButton CreateAccountButton;
    public javax.swing.JLabel DontHaveAccountYetLabel;
    public javax.swing.JLabel ForgotPasswordLabel;
    public javax.swing.JButton LoginButton;
    public javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel PCULogoLabel;
    public javax.swing.JPanel PanelBar;
    public javax.swing.JPanel PanelFrame;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel PhillipineLabel;
    private javax.swing.JCheckBox RememberMeCheckBox;
    private javax.swing.JPanel SideBar;
    public javax.swing.JLabel UniversityLabel;
    public javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    // End of variables declaration//GEN-END:variables
}
