package group1.studentinfosystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joshu
 */
public class PersonalInfo extends javax.swing.JFrame {

    /**
     * Creates new form PersonalInfo
     */
    public PersonalInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperBarPanel = new javax.swing.JPanel();
        PCULabel = new javax.swing.JLabel();
        PCULogo = new javax.swing.JLabel();
        PersonalInfoLabel = new javax.swing.JLabel();
        givenNameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        surnameLabel = new javax.swing.JLabel();
        GivenNameLabel = new javax.swing.JLabel();
        MiddleNameTextField = new javax.swing.JTextField();
        MiddleNameLabel = new javax.swing.JLabel();
        MiddleInitialTextField = new javax.swing.JTextField();
        ExtensionTextField = new javax.swing.JTextField();
        MiddleInitialLabel = new javax.swing.JLabel();
        ExtensionLabel = new javax.swing.JLabel();
        BrowseImageLabel = new javax.swing.JLabel();
        DateofBirthLabel = new javax.swing.JLabel();
        PlaceofBirthTextField = new javax.swing.JTextField();
        PlaceofBirthLabel = new javax.swing.JLabel();
        CivilStatusComboBox = new javax.swing.JComboBox<>();
        CivilStatusLabel = new javax.swing.JLabel();
        GenderComboBox = new javax.swing.JComboBox<>();
        GenderLabel = new javax.swing.JLabel();
        PresentAddressLabel = new javax.swing.JLabel();
        HouseNoTextField = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        ProvinceComboBox = new javax.swing.JComboBox<>();
        ProvinceLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        CityComboBox = new javax.swing.JComboBox<>();
        BarangayLabel = new javax.swing.JLabel();
        BarangayComboBox = new javax.swing.JComboBox<>();
        DateofBirthTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        NationalityLabel = new javax.swing.JLabel();
        ReligionLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        TelephoneNumberTextField = new javax.swing.JTextField();
        TelephoneNumberLabel = new javax.swing.JLabel();
        MobileNumberTextField = new javax.swing.JTextField();
        MobileNumberLabel = new javax.swing.JLabel();
        PreviousLabel = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();
        ImageLogoLabel = new javax.swing.JLabel();
        NationalityComboBox = new javax.swing.JComboBox<>();
        ReligionComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(968, 1061));

        UpperBarPanel.setBackground(new java.awt.Color(86, 123, 247));

        PCULabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        PCULabel.setForeground(new java.awt.Color(255, 255, 255));
        PCULabel.setText("Philippine Christian University");

        PCULogo.setIcon(new javax.swing.ImageIcon("/Users/jomari/Downloads/Philippine_Christian_University_60.png")); // NOI18N

        javax.swing.GroupLayout UpperBarPanelLayout = new javax.swing.GroupLayout(UpperBarPanel);
        UpperBarPanel.setLayout(UpperBarPanelLayout);
        UpperBarPanelLayout.setHorizontalGroup(
            UpperBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpperBarPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(PCULogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PCULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        UpperBarPanelLayout.setVerticalGroup(
            UpperBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperBarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PCULabel)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(UpperBarPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(PCULogo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PersonalInfoLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        PersonalInfoLabel.setForeground(new java.awt.Color(0, 0, 0));
        PersonalInfoLabel.setText("Your Personal Information:");

        givenNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                givenNameTextFieldActionPerformed(evt);
            }
        });

        surnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextFieldActionPerformed(evt);
            }
        });

        surnameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        surnameLabel.setForeground(new java.awt.Color(0, 0, 0));
        surnameLabel.setText("Surname:");

        GivenNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GivenNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        GivenNameLabel.setText("Given Name:");

        MiddleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleNameTextFieldActionPerformed(evt);
            }
        });

        MiddleNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MiddleNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        MiddleNameLabel.setText("Middle Name:");

        MiddleInitialTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleInitialTextFieldActionPerformed(evt);
            }
        });

        ExtensionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtensionTextFieldActionPerformed(evt);
            }
        });

        MiddleInitialLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MiddleInitialLabel.setForeground(new java.awt.Color(0, 0, 0));
        MiddleInitialLabel.setText("M.I.");

        ExtensionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ExtensionLabel.setForeground(new java.awt.Color(0, 0, 0));
        ExtensionLabel.setText("Ext.");

        BrowseImageLabel.setForeground(new java.awt.Color(0, 153, 255));
        BrowseImageLabel.setText("Browse Image");

        DateofBirthLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DateofBirthLabel.setForeground(new java.awt.Color(0, 0, 0));
        DateofBirthLabel.setText("Date of Birth: (MM/DD/YYYY)");

        PlaceofBirthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceofBirthTextFieldActionPerformed(evt);
            }
        });

        PlaceofBirthLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PlaceofBirthLabel.setForeground(new java.awt.Color(0, 0, 0));
        PlaceofBirthLabel.setText("Place of Birth:");

        CivilStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Single", "Married" }));
        CivilStatusComboBox.setBorder(null);

        CivilStatusLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CivilStatusLabel.setForeground(new java.awt.Color(0, 0, 0));
        CivilStatusLabel.setText("Civil Status:");

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Non-binary" }));
        GenderComboBox.setBorder(null);
        GenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderComboBoxActionPerformed(evt);
            }
        });

        GenderLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(0, 0, 0));
        GenderLabel.setText("Gender:");

        PresentAddressLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        PresentAddressLabel.setForeground(new java.awt.Color(0, 0, 0));
        PresentAddressLabel.setText("Present Address:");

        HouseNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HouseNoTextFieldActionPerformed(evt);
            }
        });

        AddressLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(0, 0, 0));
        AddressLabel.setText("House No, Street Name:");

        ProvinceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Region", "Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan", "Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino", "Aurora", "Bataan", "Bulacan", "Nueva Ecija", "Pampanga", "Tarlac", "Zambales", "Batangas", "Cavite", "Laguna", "Quezon", "Rizal", "Marinduque", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Romblon", "Albay", "Camarines Norte", "Camarines Sur", "Catanduanes", "Masbate", "Sorsogon", "Abra", "Apayao", "Benguet", "Ifugao", "Kalinga", "Mountain Province", "Aklan", "Antique", "Capiz", "Guimaras", "Iloilo", "Negros Occidental", "Bohol", "Cebu", "Negros Oriental", "Siquijor", "Biliran", "Eastern Samar", "Leyte", "Northern Samar", "Samar", "Southern Leyte", "Zamboanga del Norte", "Zamboanga del Sur", "Zamboanga Sibugay", "Bukidnon", "Camiguin", "Lanao del Norte", "Misamis Occidental", "Misamis Oriental", "Davao de Oro", "Davao del Norte", "Davao del Sur", "Davao Occidental", "Davao Oriental", "Cotabato", "Sarangani", "South Cotabato", "Sultan Kudarat", "Agusan del Norte", "Agusan del Sur", "Dinagat Islands", "Surigao del Norte", "Surigao del Sur", "Basilan", "Lanao del Sur", "Maguindanao del Norte", "Maguindanao del Sur", "Sulu", "Tawi-Tawi" }));
        ProvinceComboBox.setBorder(null);

        ProvinceLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ProvinceLabel.setForeground(new java.awt.Color(0, 0, 0));
        ProvinceLabel.setText("Province / Region:");

        CityLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(0, 0, 0));
        CityLabel.setText("City:");

        CityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City", "Single", "Married" }));
        CityComboBox.setBorder(null);
        CityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityComboBoxActionPerformed(evt);
            }
        });

        BarangayLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BarangayLabel.setForeground(new java.awt.Color(0, 0, 0));
        BarangayLabel.setText("Barangay:");

        BarangayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Single", "Married" }));
        BarangayComboBox.setBorder(null);
        BarangayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangayComboBoxActionPerformed(evt);
            }
        });

        DateofBirthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateofBirthTextFieldActionPerformed(evt);
            }
        });

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        NationalityLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NationalityLabel.setForeground(new java.awt.Color(0, 0, 0));
        NationalityLabel.setText("Nationality:");

        ReligionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ReligionLabel.setForeground(new java.awt.Color(0, 0, 0));
        ReligionLabel.setText("Religion:");

        EmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel.setText("Email:");

        TelephoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneNumberTextFieldActionPerformed(evt);
            }
        });

        TelephoneNumberLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TelephoneNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        TelephoneNumberLabel.setText("Telephone Number:");

        MobileNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNumberTextFieldActionPerformed(evt);
            }
        });

        MobileNumberLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MobileNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        MobileNumberLabel.setText("Mobile Number:");

        PreviousLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PreviousLabel.setForeground(new java.awt.Color(0, 153, 255));
        PreviousLabel.setText("Previous");

        NextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NextLabel.setForeground(new java.awt.Color(0, 153, 255));
        NextLabel.setText("Next");

        ImageLogoLabel.setIcon(new javax.swing.ImageIcon("/Users/jomari/Downloads/posa4.jpg")); // NOI18N
        ImageLogoLabel.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ImageLogoLabelInputMethodTextChanged(evt);
            }
        });

        NationalityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Region", "Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan", "Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino", "Aurora", "Bataan", "Bulacan", "Nueva Ecija", "Pampanga", "Tarlac", "Zambales", "Batangas", "Cavite", "Laguna", "Quezon", "Rizal", "Marinduque", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Romblon", "Albay", "Camarines Norte", "Camarines Sur", "Catanduanes", "Masbate", "Sorsogon", "Abra", "Apayao", "Benguet", "Ifugao", "Kalinga", "Mountain Province", "Aklan", "Antique", "Capiz", "Guimaras", "Iloilo", "Negros Occidental", "Bohol", "Cebu", "Negros Oriental", "Siquijor", "Biliran", "Eastern Samar", "Leyte", "Northern Samar", "Samar", "Southern Leyte", "Zamboanga del Norte", "Zamboanga del Sur", "Zamboanga Sibugay", "Bukidnon", "Camiguin", "Lanao del Norte", "Misamis Occidental", "Misamis Oriental", "Davao de Oro", "Davao del Norte", "Davao del Sur", "Davao Occidental", "Davao Oriental", "Cotabato", "Sarangani", "South Cotabato", "Sultan Kudarat", "Agusan del Norte", "Agusan del Sur", "Dinagat Islands", "Surigao del Norte", "Surigao del Sur", "Basilan", "Lanao del Sur", "Maguindanao del Norte", "Maguindanao del Sur", "Sulu", "Tawi-Tawi" }));
        NationalityComboBox.setBorder(null);

        ReligionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Religion", "Roman Catholic", "Iglesia ni Cristo", "Islam", "Protestantism", "Baptist", "Others" }));
        ReligionComboBox.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ProvinceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ProvinceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(NationalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NationalityComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReligionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReligionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(NextLabel)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BarangayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BarangayComboBox, 0, 159, Short.MAX_VALUE)
                                            .addComponent(EmailTextField)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TelephoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TelephoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MobileNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MobileNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(HouseNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PresentAddressLabel)
                            .addComponent(AddressLabel)
                            .addComponent(PreviousLabel))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MiddleNameLabel)
                                .addGap(112, 112, 112)
                                .addComponent(MiddleInitialLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateofBirthLabel)
                                .addGap(18, 18, 18)
                                .addComponent(PlaceofBirthLabel))
                            .addComponent(MiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateofBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PlaceofBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CivilStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CivilStatusLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GenderLabel)
                                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ImageLogoLabel)
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BrowseImageLabel)
                                        .addGap(67, 67, 67))))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(surnameLabel)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GivenNameLabel)
                            .addComponent(givenNameTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MiddleInitialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExtensionLabel)
                                    .addComponent(ExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(PersonalInfoLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpperBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PersonalInfoLabel)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(givenNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameLabel)
                            .addComponent(GivenNameLabel))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MiddleInitialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ImageLogoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MiddleNameLabel)
                    .addComponent(MiddleInitialLabel)
                    .addComponent(ExtensionLabel)
                    .addComponent(BrowseImageLabel))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaceofBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CivilStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateofBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateofBirthLabel)
                    .addComponent(PlaceofBirthLabel)
                    .addComponent(CivilStatusLabel)
                    .addComponent(GenderLabel))
                .addGap(18, 18, 18)
                .addComponent(PresentAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HouseNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProvinceLabel)
                        .addGap(5, 5, 5)
                        .addComponent(ProvinceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(NationalityLabel)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CityLabel)
                            .addComponent(BarangayLabel))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarangayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReligionLabel)
                            .addComponent(EmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NationalityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReligionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelephoneNumberLabel)
                    .addComponent(MobileNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelephoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousLabel)
                    .addComponent(NextLabel))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void givenNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_givenNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_givenNameTextFieldActionPerformed

    private void surnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextFieldActionPerformed

    private void MiddleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddleNameTextFieldActionPerformed

    private void MiddleInitialTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleInitialTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddleInitialTextFieldActionPerformed

    private void ExtensionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtensionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtensionTextFieldActionPerformed

    private void PlaceofBirthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceofBirthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaceofBirthTextFieldActionPerformed

    private void HouseNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HouseNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HouseNoTextFieldActionPerformed

    private void GenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderComboBoxActionPerformed

    private void CityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityComboBoxActionPerformed

    private void BarangayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangayComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarangayComboBoxActionPerformed

    private void DateofBirthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateofBirthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateofBirthTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void TelephoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneNumberTextFieldActionPerformed

    private void MobileNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNumberTextFieldActionPerformed

    private void ImageLogoLabelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ImageLogoLabelInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ImageLogoLabelInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JComboBox<String> BarangayComboBox;
    private javax.swing.JLabel BarangayLabel;
    private javax.swing.JLabel BrowseImageLabel;
    private javax.swing.JComboBox<String> CityComboBox;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JComboBox<String> CivilStatusComboBox;
    private javax.swing.JLabel CivilStatusLabel;
    private javax.swing.JLabel DateofBirthLabel;
    private javax.swing.JTextField DateofBirthTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel ExtensionLabel;
    private javax.swing.JTextField ExtensionTextField;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel GivenNameLabel;
    private javax.swing.JTextField HouseNoTextField;
    private javax.swing.JLabel ImageLogoLabel;
    private javax.swing.JLabel MiddleInitialLabel;
    private javax.swing.JTextField MiddleInitialTextField;
    private javax.swing.JLabel MiddleNameLabel;
    private javax.swing.JTextField MiddleNameTextField;
    private javax.swing.JLabel MobileNumberLabel;
    private javax.swing.JTextField MobileNumberTextField;
    public javax.swing.JComboBox<String> NationalityComboBox;
    private javax.swing.JLabel NationalityLabel;
    private javax.swing.JLabel NextLabel;
    private javax.swing.JLabel PCULabel;
    private javax.swing.JLabel PCULogo;
    private javax.swing.JLabel PersonalInfoLabel;
    private javax.swing.JLabel PlaceofBirthLabel;
    private javax.swing.JTextField PlaceofBirthTextField;
    private javax.swing.JLabel PresentAddressLabel;
    private javax.swing.JLabel PreviousLabel;
    private javax.swing.JComboBox<String> ProvinceComboBox;
    private javax.swing.JLabel ProvinceLabel;
    public javax.swing.JComboBox<String> ReligionComboBox;
    private javax.swing.JLabel ReligionLabel;
    public javax.swing.JLabel TelephoneNumberLabel;
    private javax.swing.JTextField TelephoneNumberTextField;
    private javax.swing.JPanel UpperBarPanel;
    private javax.swing.JTextField givenNameTextField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTextField;
    // End of variables declaration//GEN-END:variables
}
